//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopping.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Members
    {
        public Tbl_Members()
        {
            this.Tbl_Cart = new HashSet<Tbl_Cart>();
            this.Tbl_Cart1 = new HashSet<Tbl_Cart>();
        }
    
        public int MemberId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string EmailId { get; set; }
        public string Password { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<bool> IsDelete { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> DOB { get; set; }
        public Nullable<int> GenderId { get; set; }
        public string PhoneNo { get; set; }
        public string ProfilePic { get; set; }
    
        public virtual ICollection<Tbl_Cart> Tbl_Cart { get; set; }
        public virtual ICollection<Tbl_Cart> Tbl_Cart1 { get; set; }
    }
}
