//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopping.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Roles
    {
        public Tbl_Roles()
        {
            this.Tbl_MemberRole = new HashSet<Tbl_MemberRole>();
        }
    
        public int RoleId { get; set; }
        public string RoleName { get; set; }
    
        public virtual ICollection<Tbl_MemberRole> Tbl_MemberRole { get; set; }
    }
}
