//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopping.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_CartStatus
    {
        public Tbl_CartStatus()
        {
            this.Tbl_Cart = new HashSet<Tbl_Cart>();
            this.Tbl_Cart1 = new HashSet<Tbl_Cart>();
        }
    
        public int CartStatusId { get; set; }
        public string CartStatus { get; set; }
    
        public virtual ICollection<Tbl_Cart> Tbl_Cart { get; set; }
        public virtual ICollection<Tbl_Cart> Tbl_Cart1 { get; set; }
    }
}
